
version: '3.3'

services:

  letsencrypt:
    image: asamoshkin/letsencrypt-certgen
    command: issue
    volumes:
      - ./$HOST_CERT_DIR:/var/ssl
    ports:
      - "80:80"
    environment:
      # LETSENCRYPT_EMAIL: ${EMAIL}
      DOMAINS: ${DOMAIN}

  pusher:
    build:
      context: ./builds/s3push
      args:
        PYTHON_RELEASE: ${PYTHON_RELEASE}
    command: /scripts/push.py
    working_dir: /data
    volumes:
      - ./$HOST_CERT_DIR/$DOMAIN:/data
      - ./scripts:/scripts
    environment:
      APP_ENV: ${ENVIRONMENT}
